[NeutralGunRoom, false] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom1, false] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom2, false] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom, false] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom1, false] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom2, false] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom, true] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom1, true] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom2, true] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Gun Control Room!"] remoteExec ["globalchat", 2];