[NeutralHanger, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger, false] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger1, false] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger2, false] remoteExec ["hideObjectGlobal", 2];
[CISHanger, true] remoteExec ["hideObjectGlobal", 2];
[CISHanger1, true] remoteExec ["hideObjectGlobal", 2];
[CISHanger2, true] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the hanger!"] remoteExec ["globalchat", 2];