[NeutralCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter, false] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter1, false] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter2, false] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Command Center!"] remoteExec ["globalchat", 2];