[Gate_10_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_10_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_10_2, true] remoteExec ["hideObjectGlobal", 2];