[Gate_13_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_13_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_13_2, true] remoteExec ["hideObjectGlobal", 2];