[Gate_12_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_12_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_12_2, true] remoteExec ["hideObjectGlobal", 2];