[Gate_9_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_9_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_9_2, true] remoteExec ["hideObjectGlobal", 2];