[Gate_1_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_1_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_1_2, true] remoteExec ["hideObjectGlobal", 2];