[Gate_3_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_3_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_3_2, true] remoteExec ["hideObjectGlobal", 2];