[Gate_4_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_4_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_4_14, false] remoteExec ["hideObjectGlobal", 2];