[Gate_15_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_15_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_15_14, false] remoteExec ["hideObjectGlobal", 2];