[Gate_8_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_8_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_8_14, false] remoteExec ["hideObjectGlobal", 2];