[Gate_11_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_11_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_11_14, false] remoteExec ["hideObjectGlobal", 2];