[NeutralBrig, true] remoteExec ["hideObjectGlobal", 2];
[NeutralBrig1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralBrig2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig2, true] remoteExec ["hideObjectGlobal", 2];
[CISBrig, false] remoteExec ["hideObjectGlobal", 2];
[CISBrig1, false] remoteExec ["hideObjectGlobal", 2];
[CISBrig2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Command Center!"] remoteExec ["globalchat", 2];