_caller = _this select 1;
[NeutralHanger, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger, false] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger1, false] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger2, false] remoteExec ["hideObjectGlobal", 2];
[CISHanger, true] remoteExec ["hideObjectGlobal", 2];
[CISHanger1, true] remoteExec ["hideObjectGlobal", 2];
[CISHanger2, true] remoteExec ["hideObjectGlobal", 2];
_caller globalChat "I have captured the Hanger!";