_Range1Droid = creategroup [east, true];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid1, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid1); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid2, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid2); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid3, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid3); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid4, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid4); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid5, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid5); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid6, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid6); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid7, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid7); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid8, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid8); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid9, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid9); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range1Line1Droid10, _Range1Droid, "this setPosASL (getPosASL Range1Line1Droid10); this disableAI 'ALL';"];
Range1Line1Wall1 hideobjectglobal false;
Range1Line1Wall2 hideobjectglobal false;
Range1Line1Wall3 hideobjectglobal false;
Range1Line1Wall4 hideobjectglobal false;
Range1Line2Wall1 hideobjectglobal true;
Range1Line2Wall2 hideobjectglobal true;
Range1Line2Wall3 hideobjectglobal true;
Range1Line2Wall4 hideobjectglobal true;
Range1Line3Wall1 hideobjectglobal true;
Range1Line3Wall2 hideobjectglobal true;
Range1Line3Wall3 hideobjectglobal true;
Range1Line3Wall4 hideobjectglobal true;