_Range3Droid = creategroup [east, true];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid1, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid1); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid2, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid2); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid3, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid3); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid4, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid4); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid5, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid5); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid6, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid6); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid7, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid7); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid8, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid8); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid9, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid9); this disableAI 'ALL';"];
"SWOP_CIS_Droid" createUnit [position Range3Line2Droid10, _Range3Droid, "this setPosASL (getPosASL Range3Line2Droid10); this disableAI 'ALL';"];
Range3Line1Wall1 hideobjectglobal true;
Range3Line1Wall2 hideobjectglobal true;
Range3Line1Wall3 hideobjectglobal true;
Range3Line1Wall4 hideobjectglobal true;
Range3Line2Wall1 hideobjectglobal false;
Range3Line2Wall2 hideobjectglobal false;
Range3Line2Wall3 hideobjectglobal false;
Range3Line2Wall4 hideobjectglobal false;
Range3Line3Wall1 hideobjectglobal true;
Range3Line3Wall2 hideobjectglobal true;
Range3Line3Wall3 hideobjectglobal true;
Range3Line3Wall4 hideobjectglobal true;