sleep 7;
Comment "1st Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "2nd Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "3rd Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "4th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "5th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "6th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "7th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "8th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "9th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
Comment "10th Charges";
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
sleep 3;
[LAAT_Wreck_096, true] remoteExec ["hideObjectGlobal", 2];
[Munificent, true] remoteExec ["hideObjectGlobal", 2];
[a, true] remoteExec ["hideObjectGlobal", 2];
[b, true] remoteExec ["hideObjectGlobal", 2];
[c, true] remoteExec ["hideObjectGlobal", 2];
[d, true] remoteExec ["hideObjectGlobal", 2];
[e, true] remoteExec ["hideObjectGlobal", 2];
[f, true] remoteExec ["hideObjectGlobal", 2];
[m, true] remoteExec ["hideObjectGlobal", 2];
[n, true] remoteExec ["hideObjectGlobal", 2];
[o, true] remoteExec ["hideObjectGlobal", 2];
[p, true] remoteExec ["hideObjectGlobal", 2];
[j, true] remoteExec ["hideObjectGlobal", 2];
[k, true] remoteExec ["hideObjectGlobal", 2];
[l, true] remoteExec ["hideObjectGlobal", 2];
[h, true] remoteExec ["hideObjectGlobal", 2];
[g, true] remoteExec ["hideObjectGlobal", 2];
[Laser1, true] remoteExec ["hideObjectGlobal", 2];
[Laser2, true] remoteExec ["hideObjectGlobal", 2];
[Laser3, true] remoteExec ["hideObjectGlobal", 2];
[Laser4, true] remoteExec ["hideObjectGlobal", 2];
[Laser5, true] remoteExec ["hideObjectGlobal", 2];
[Laser6, true] remoteExec ["hideObjectGlobal", 2];
[Laser7, true] remoteExec ["hideObjectGlobal", 2];
[Laser8, true] remoteExec ["hideObjectGlobal", 2];
[Laser9, true] remoteExec ["hideObjectGlobal", 2];
[Laser10, true] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 1;
[Munificent_1, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_1, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_1, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_1, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_1, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_1, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_1, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_1, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_1, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_1, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_1, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_1, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_1, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_2, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_2, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_2, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_2, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_2, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_2, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_2, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_2, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_2, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_2, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_2, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_2, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_2, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_3, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_3, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_3, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_3, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_3, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_3, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_3, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_3, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_3, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_3, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_3, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_3, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_3, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_4, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_4, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_4, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_4, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_4, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_4, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_4, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_4, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_4, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_4, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_4, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_4, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_4, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_5, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_5, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_5, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_5, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_5, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_5, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_5, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_5, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_5, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_5, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_5, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_5, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_5, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_6, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_6, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_6, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_6, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_6, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_6, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_6, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_6, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_6, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_6, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_6, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_6, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_6, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_7, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_7, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_7, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_7, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_7, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_7, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_7, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_7, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_7, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_7, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_7, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_7, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_7, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_7, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_8, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_8, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_8, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_8, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_8, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_8, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_8, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_8, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_8, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_8, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_8, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_8, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_8, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_8, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_9,false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_9, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_9, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_9, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_9, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_9, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_9, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_9, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_9, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_9, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_9, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_9, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_9, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_9, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_10, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_10, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_10, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_10, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_10, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_10, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_10, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_10, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_10, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_10, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_10, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_10, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_10, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_10, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_11, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_11, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_11, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_11, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_11, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_11, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_11, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_11, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_11, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_11, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_11, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_11, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_11, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_11, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_12, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_12, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_12, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_12, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_12, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_12, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_12, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_12, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_12, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_12, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_12, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_12, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_12, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_12, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_13, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_13, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_13, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_13, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_13, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_13, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_13, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_13, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_13, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_13, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_13, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_13, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_13, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_13, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_14, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_14, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_14, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_14, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_14, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_14, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_14, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_14, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_14, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_14, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_14, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_14, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_14, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 3;
[Munificent_14, true] remoteExec ["hideObjectGlobal", 2];
[Munificent_15, false] remoteExec ["hideObjectGlobal", 2];
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_15, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_15, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_15, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_15, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_15, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_15, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 2;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object1_15, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object2_15, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object3_15, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object4_15, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object5_15, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position object6_15, [], 0, "NONE"];
_charge5 setdamage 1;
sleep 1;
_charge = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box, [], 0, "NONE"];
_charge setdamage 1;
_charge1 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_1, [], 0, "NONE"];
_charge1 setdamage 1;
_charge2 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_2, [], 0, "NONE"];
_charge2 setdamage 1;
_charge3 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_3, [], 0, "NONE"];
_charge3 setdamage 1;
_charge4 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_4, [], 0, "NONE"];
_charge4 setdamage 1;
_charge5 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_5, [], 0, "NONE"];
_charge5 setdamage 1;
_charge6 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_6, [], 0, "NONE"];
_charge6 setdamage 1;
_charge7 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_7, [], 0, "NONE"];
_charge7 setdamage 1;
_charge8 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_8, [], 0, "NONE"];
_charge8 setdamage 1;
_charge9 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_9, [], 0, "NONE"];
_charge9 setdamage 1;
_charge10 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_10, [], 0, "NONE"];
_charge10 setdamage 1;
_charge11 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_11, [], 0, "NONE"];
_charge11 setdamage 1;
_charge12 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_12, [], 0, "NONE"];
_charge12 setdamage 1;
_charge13 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_13, [], 0, "NONE"];
_charge13 setdamage 1;
_charge14 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_14, [], 0, "NONE"];
_charge14 setdamage 1;
_charge15 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_15, [], 0, "NONE"];
_charge15 setdamage 1;
_charge16 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_16, [], 0, "NONE"];
_charge16 setdamage 1;
_charge17 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_17, [], 0, "NONE"];
_charge17 setdamage 1;
_charge18 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_18, [], 0, "NONE"];
_charge18 setdamage 1;
_charge19 = createVehicle ["SatchelCharge_Remote_Ammo_Scripted", Position box_19, [], 0, "NONE"];
_charge19 setdamage 1;