[NeutralDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab, false] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab1, false] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Droid Fab!"] remoteExec ["globalchat", 2];