[NeutralDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab, false] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab1, false] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab2, false] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Droid Fab!"] remoteExec ["globalchat", 2];