Comment "Hanger CPs";
[NeutralHanger, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralHanger2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger, true] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicHanger2, true] remoteExec ["hideObjectGlobal", 2];
[CISHanger, false] remoteExec ["hideObjectGlobal", 2];
[CISHanger1, false] remoteExec ["hideObjectGlobal", 2];
[CISHanger2, false] remoteExec ["hideObjectGlobal", 2];
Comment "Brig CPs";
[NeutralBrig, true] remoteExec ["hideObjectGlobal", 2];
[NeutralBrig1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralBrig2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBrig2, true] remoteExec ["hideObjectGlobal", 2];
[CISBrig, false] remoteExec ["hideObjectGlobal", 2];
[CISBrig1, false] remoteExec ["hideObjectGlobal", 2];
[CISBrig2, false] remoteExec ["hideObjectGlobal", 2];
Comment "Command Center CPs";
[NeutralCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter, false] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter1, false] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter2, false] remoteExec ["hideObjectGlobal", 2];
Comment "Generator CPs";
[NeutralGen, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGen1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGen2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGen, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGen1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGen2, true] remoteExec ["hideObjectGlobal", 2];
[CISGen, false] remoteExec ["hideObjectGlobal", 2];
[CISGen1, false] remoteExec ["hideObjectGlobal", 2];
[CISGen2, false] remoteExec ["hideObjectGlobal", 2];
Comment "Droid Fab CPs";
[NeutralDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicDroidFab2, true] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab, false] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab1, false] remoteExec ["hideObjectGlobal", 2];
[CISDroidFab2, false] remoteExec ["hideObjectGlobal", 2];
Comment "Bridge CPs";
[NeutralBridge, true] remoteExec ["hideObjectGlobal", 2];
[NeutralBridge1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBridge, true] remoteExec ["hideObjectGlobal", 2];
[RepublicBridge1, true] remoteExec ["hideObjectGlobal", 2];
[CISBridge, false] remoteExec ["hideObjectGlobal", 2];
[CISBridge1, false] remoteExec ["hideObjectGlobal", 2];
Comment "Gun Control Room CPs";
[NeutralGunRoom, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom2, true] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom, false] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom1, false] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have reset the ship!"] remoteExec ["globalchat", 2];