_House2Droid = creategroup [east, true];
_House2Civ = creategroup [civilian, true];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid1, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid1); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid2, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid2); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid3, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid3); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid4, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid4); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid5, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid5); this disableAI 'PATH';"];
"SWOP_CIS_SuperDroid_B2" createUnit [position House2Temp1Droid6, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid6); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid7, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid7); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid8, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid8); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid9, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid9); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House2Temp1Droid10, _House2Droid, "this setPosASL (getPosASL House2Temp1Droid10); this disableAI 'PATH';"];
"C_man_1" createUnit [position House2Temp1Civ1, _House2Civ, "this setPosASL (getPosASL House2Temp1Civ1); this disableAI 'PATH';"];
"SWOP_CIS_Droid_Tactic_Blue" createUnit [position House2Temp1Civ2, _House2Civ, "this setPosASL (getPosASL House2Temp1Civ2); this disableAI 'ALL'; removeAllWeapons this;"];