_House1Droid = creategroup [east, true];
_House1Civ = creategroup [civilian, true];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid1, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid1); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid2, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid2); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid3, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid3); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid4, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid4); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid5, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid5); this disableAI 'PATH';"];
"SWOP_CIS_SuperDroid_B2" createUnit [position House1Temp2Droid6, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid6); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid7, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid7); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid8, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid8); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid9, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid9); this disableAI 'PATH';"];
"SWOP_CIS_Droid" createUnit [position House1Temp2Droid10, _House1Droid, "this setPosASL (getPosASL House1Temp2Droid10); this disableAI 'PATH';"];
"C_man_1" createUnit [position House1Temp2Civ1, _House1Civ, "this setPosASL (getPosASL House1Temp2Civ1); this disableAI 'PATH';"];
"SWOP_CIS_Droid_Tactic_Blue" createUnit [position House1Temp2Civ2, _House1Civ, "this setPosASL (getPosASL House1Temp2Civ2); this disableAI 'ALL'; removeAllWeapons this;"];