[NeutralCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicCommandCenter2, true] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter, false] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter1, false] remoteExec ["hideObjectGlobal", 2];
[CISCommandCenter2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Command Center!"] remoteExec ["globalchat", 2];