[NeutralGunRoom, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGunRoom2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGunRoom2, true] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom, false] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom1, false] remoteExec ["hideObjectGlobal", 2];
[CISGunRoom2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Gun Control Room!"] remoteExec ["globalchat", 2];