[NeutralGenerator, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGenerator1, true] remoteExec ["hideObjectGlobal", 2];
[NeutralGenerator2, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGenerator, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGenerator1, true] remoteExec ["hideObjectGlobal", 2];
[RepublicGenerator2, true] remoteExec ["hideObjectGlobal", 2];
[CISGenerator, false] remoteExec ["hideObjectGlobal", 2];
[CISGenerator1, false] remoteExec ["hideObjectGlobal", 2];
[CISGenerator2, false] remoteExec ["hideObjectGlobal", 2];
[player, "I have captured the Generator!"] remoteExec ["globalchat", 2];