[Gate_6_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_6_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_6_2, true] remoteExec ["hideObjectGlobal", 2];