[Gate_7_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_7_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_7_2, true] remoteExec ["hideObjectGlobal", 2];