[Gate_16_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_16_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_16_2, true] remoteExec ["hideObjectGlobal", 2];