[Gate_2_13, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_14, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_12, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_13, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_11, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_12, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_10, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_11, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_9, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_10, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_8, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_9, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_7, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_8, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_6, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_7, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_5, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_6, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_4, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_5, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_3, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_4, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_2, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_3, true] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_2_1, false] remoteExec ["hideObjectGlobal", 2];
[Gate_2_2, true] remoteExec ["hideObjectGlobal", 2];