[Airbase_Gate_1, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_2, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_3, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_4, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_5, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_6, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_7, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_8, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_9, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_10, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_11, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_12, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Airbase_Gate_13, true] remoteExec ["hideObjectGlobal", 2];
[Airbase_Gate_14, false] remoteExec ["hideObjectGlobal", 2];