[Gate_14_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_14_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_14_14, false] remoteExec ["hideObjectGlobal", 2];