[Gate_5_1, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_2, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_2, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_3, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_3, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_4, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_4, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_5, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_5, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_6, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_6, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_7, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_7, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_8, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_8, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_9, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_9, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_10, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_10, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_11, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_11, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_12, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_12, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_13, false] remoteExec ["hideObjectGlobal", 2];
sleep 2;
[Gate_5_13, true] remoteExec ["hideObjectGlobal", 2];
[Gate_5_14, false] remoteExec ["hideObjectGlobal", 2];