//Created by Rexi
	params["_vic"];
	_vic enablesimulation true;
	clearItemCargoGlobal _vic;
	clearMagazineCargoGlobal _vic;
	clearweaponCargoGlobal _vic;
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Low_Mag", 50]; 
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Full_Mag", 50]; 
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Mag", 50]; 
	_vic addMagazineCargoGlobal ["DCStun_Mag", 15]; 	
	_vic addMagazineCargoGlobal ["SWOP_DC15_Mag", 25];
	_vic addMagazineCargoGlobal ["300Rnd_BlasterLaser_Belt", 25];
	_vic addMagazineCargoGlobal [ "RocketHH15CloneHEATFF_Mag", 10];
	_vic addMagazineCargoGlobal [ "RocketHH15CloneHEATFF_Mag_RD501", 10];
	_vic addItemCargoGlobal ["SWOP_termDet_G", 20];
	_vic addItemCargoGlobal ["SmokeShell", 20];
	_vic addItemCargoGlobal ["SWOPthrowablectype", 2];
	_vic addweaponcargoglobal ["SWOP_DC15ABlasterRifle_RD501",5];
	_vic addMagazineCargoGlobal ["SWOP_dc15xBlasterRifle_RD501_Mag", 5]; 
	_vic addMagazineCargoGlobal ["5Rnd_HE_Grenade_DC15A", 10]; 
	
	
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Low_highcap_Mag", 5];
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Low_highcap_box_Mag", 5];
	_vic addMagazineCargoGlobal ["5Rnd_HE_Grenade_DC15A", 10];
	_vic addMagazineCargoGlobal ["1Rnd_AT_Grenade_DC15A",  5];      
	_vic addMagazineCargoGlobal ["UGL_FlareWhite_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareGreen_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareRed_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareYellow_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareCIR_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareBlue_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlareCyan_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["UGL_FlarePurple_F_3Rnd_RD501", 10];
	_vic addMagazineCargoGlobal ["3Rnd_Smoke_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokeRed_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokeGreen_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokeYellow_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokePurple_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokeBlue_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["3Rnd_SmokeOrange_Grenade_shell", 10];
	_vic addMagazineCargoGlobal ["ACE_HuntIR_M203", 10];
	_vic addMagazineCargoGlobal ["SWOP_DC17Pistol_Mag", 15]; 
	_vic addMagazineCargoGlobal ["DCStun_DC17_Mag" , 15];
	_vic addMagazineCargoGlobal ["SWOP_WESTARM5_MAG", 25];
	_vic addMagazineCargoGlobal ["SWOP_Westar35Pistol_Mag", 30];
	ACE_maxWeightCarry = 20000;	