//Created by Rexi
	params["_vic"];
	_vic enablesimulation true;
	clearItemCargoGlobal _vic;
	clearMagazineCargoGlobal _vic;
	clearweaponCargoGlobal _vic;
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Low_Mag", 50]; 
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Full_Mag", 50]; 
	_vic addMagazineCargoGlobal ["SWOP_DC15ABlasterRifle_Mag", 50]; 
	_vic addMagazineCargoGlobal ["DCStun_Mag", 15]; 	
	_vic addMagazineCargoGlobal ["SWOP_DC15_Mag", 25];
	_vic addMagazineCargoGlobal ["300Rnd_BlasterLaser_Belt", 30];
	_vic addMagazineCargoGlobal [ "RocketHH15CloneHEATFF_Mag", 10];
	_vic addItemCargoGlobal ["SWOP_termDet_G", 20];
	_vic addItemCargoGlobal ["SmokeShell", 20];
	_vic addItemCargoGlobal ["SWOPthrowablectype", 2];
	_vic addweaponcargoglobal ["SWOP_DC15ABlasterRifle",5];
	_vic addMagazineCargoGlobal ["SWOP_Valken38XBlasterRifle_Mag", 5]; 
	_vic addMagazineCargoGlobal ["5Rnd_HE_Grenade_DC15A", 10]; 
	ACE_maxWeightCarry = 10000;	