name: Mission Generator CI

on:
  pull_request:
    tags: ['missiongen']
  push:
    paths: ['Tools/MissionGenerator/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore "Tools/MissionGenerator/MissionGenerator.sln"
    - name: Build
      run: dotnet build --no-restore "Tools/MissionGenerator/MissionGenerator.sln"
    - name: Test
      run: dotnet test --no-build --verbosity normal "Tools/MissionGenerator/MissionGenerator.sln"
