name: Mission Generator Run

on:
  workflow_dispatch:

jobs:
  mgr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore Mission Generator dependencies
      run: dotnet restore "Tools/MissionGenerator/MissionGenerator.sln"
    - name: Build Mission Generator
      run: dotnet build --no-restore --configuration Release "Tools/MissionGenerator/MissionGenerator.sln"
    - name: Run Mission Generator
      run: 'dotnet Tools/MissionGenerator/MissionGenerator/bin/Release/net6.0/MissionGenerator.dll "Missions/Framework/" "Compositions/Generator/" "Missions/Pending/" --title "501st Legion FunOp {0}: {1} {2}" --desc "Official 501st Legion FunOP | All 501st, 212th, 91st, 101st, and 327th slots! | {0}" --missions "Missions/missions.cfg" --latest'
    - name: Git commit, pull & push action
      # You may pin to the exact commit or the version.
      # uses: mgrybyk-org/git-commit-pull-push-action@b8a0f79952cbb2a10089ef6d0a132d0f8a52fa8e
      uses: mgrybyk-org/git-commit-pull-push-action@v1.2.4
      with:
        # Local file path to the git repository. Defaults to the current directory '.'
        # repository: # default is .
        # Git branch name, where changes should be pushed to.
        branch: ${{ github.head_ref || github.ref_name }}
        # Commit message
        commit_message: Mission Generator Run
        # git pull arguments
        # pull_args: # optional, default is --rebase
        # git add arguments (eg. -u) or 'src/*.js'
        # add_args: # optional, default is .
