name: Mission File Release

on:
  workflow_dispatch:
  release:
    types: ['published']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Multipack dependencies
      run: dotnet restore "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Build Multipack Util
      run: dotnet build --no-restore --configuration Release "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Lemme See
      run: cd Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net5.0/ && ls
    - name: Lemme See more
      run: Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net5.0/Utils && ls
    - name: Run Multipack Util
      run: dotnet Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net5.0/MultiPackPBOUtil.dll "Missions/Pending/" --delete --move "Missions/Live" --output "Missions/Live/PBO" --content "Scripts" --ignore "placeholder"
    - name: Update Repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Mission File Release
        push_options: '--force'
