name: Mission File Release

on:
  workflow_dispatch:
  release:
    types: ['published']

jobs:
  rmf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Multipack dependencies
      run: dotnet restore "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Build Multipack Util
      run: dotnet build --no-restore --configuration Release "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Install Mikero Dependencies
      run: |
        sudo apt-add-repository universe
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install liblzo2-2 libvorbis0a libvorbisfile3 libvorbisenc2 libogg0 libuchardet0
        cd Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net5.0/
        cd Utils/
        tar -xzvf depbo-tools.tgz
        cd depbo-tools-0.8.10/ && ls
        cp -a lib/. /lib/
        sudo /sbin/ldconfig -v
    - name: Run Multipack Util
      run: dotnet Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net5.0/MultiPackPBOUtil.dll "Missions/Pending/" --delete --move "Missions/Live" --output "Missions/Live/PBO" --content "Scripts" --ignore "placeholder"
    - name: Update Repo
      if: ${{ !env.ACT }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Mission File Release
        push_options: '--force'
