name: Mission File Release

on:
  workflow_dispatch:

jobs:
  rmf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Multipack dependencies
      run: dotnet restore "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Build Multipack Util
      run: dotnet build --no-restore --configuration Release "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Install Mikero Dependencies
      run: |
        sudo apt-add-repository universe
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install liblzo2-2 libvorbis0a libvorbisfile3 libvorbisenc2 libogg0 libuchardet0
        cd Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net6.0/Utils/
        tar -xzvf depbo-tools.tgz
    - name: Run Multipack Util
      run: |
        export LD_LIBRARY_PATH=$(pwd)/Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net6.0/Utils/depbo-tools-0.8.60/lib:$LD_LIBRARY_PATH
        dotnet Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net6.0/MultiPackPBOUtil.dll "Missions/Pending/" --delete --move "Missions/Live" --output "mpmissions" --content "Scripts" --ignore "placeholder" --latest
    - name: Update Repo
      if: ${{ !env.ACT }}
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: Mission File Release
        #push_options: '--force'
