name: Mission File Release

on:
  workflow_dispatch:

jobs:
  rmf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore Multipack dependencies
      run: dotnet restore "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Build Multipack Util
      run: dotnet build --no-restore --configuration Release "Tools/MultiPackPBOUtil/MultiPackPBOUtil.sln"
    - name: Install Mikero Dependencies
      run: |
        sudo apt-add-repository universe
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install liblzo2-2 libvorbis0a libvorbisfile3 libvorbisenc2 libogg0 libuchardet0
        cd Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net6.0/Utils/
        tar -xzvf depbo-tools.tgz
    - name: Run Multipack Util
      run: |
        export LD_LIBRARY_PATH=$(pwd)/Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net8.0/Utils/depbo-tools-0.8.60/lib:$LD_LIBRARY_PATH
        dotnet Tools/MultiPackPBOUtil/MultiPackPBOUtil/bin/Release/net8.0/MultiPackPBOUtil.dll "Missions/Pending/" --delete --move "Missions/Live" --output "mpmissions" --content "Scripts" --ignore "placeholder" --latest
    - name: Git commit, pull & push action
      # You may pin to the exact commit or the version.
      # uses: mgrybyk-org/git-commit-pull-push-action@b8a0f79952cbb2a10089ef6d0a132d0f8a52fa8e
      uses: mgrybyk-org/git-commit-pull-push-action@v1.2.4
      with:
        # Local file path to the git repository. Defaults to the current directory '.'
        # repository: # default is .
        # Git branch name, where changes should be pushed to.
        branch: ${{ github.head_ref || github.ref_name }}
        # Commit message
        commit_message: Mission Generator Run
        # git pull arguments
        # pull_args: # optional, default is --rebase
        # git add arguments (eg. -u) or 'src/*.js'
        # add_args: # optional, default is .
